### ISSUE TITLE
Autoload history not working when revisiting page

### ISSUE THREAD

**Issue by jenscl** [pubnub/pubnub-angular2#20] opened 2017-06-15 16:28 UTC
Hi,

We use the autoload parameter and the getMessage method when subscribing to a channel. In this way we can show the last message from the history until a new one arrives. When leaving the page, the channel is unsubscribed and the stack is cleaned. When returning to this page, everything is reloaded. This all worked well in v1.0.0 beta 8.

We have updated the package to the latest version and now the history does not load anymore when visiting the page after navigating away (so we have to wait until a new message arrives). The first time everything goes well, but when we revisit the page the getMessage function is not executed. It seems this no longer works from beta 9.

Some parts of our code:

```
ngOnInit() {
    this.pubnubService.subscribe({ channels: ['device1'], triggerEvents: true, autoload: 1 });
    let history = this.pubnubService.getMessage('device1', () => {
        this.sensorValue = history[0]['message']['sensorValue'];
        history.shift();
    });
}

ngOnDestroy() {
    this.pubnubService.unsubscribe({ channels: ['device1'] });
    this.pubnubService.clean(['device1']);
}
```

How can we solve this?
Thanks in advance to help us with this problem.

**Comment by ManuelFernando** [comment] 2017-06-16 16:02
@jenscl we haven’t reproduce the bug yet but some questions are you using TS or directly from JS and the other one have you validated if the ngOnInit is executed again when you revisit the page?

**Comment by averhaegen** [comment] 2017-06-16 16:13
Hi @ManuelFernando, I'm a colleague of @jenscl, so I will respond since he just left the office :) 
We're using TS and the ngOnInit is executed every time. The problem also occurs when we manually reload the subscription on the active page. 

I've noticed you [committed ](https://github.com/pubnub/pubnub-angular2/commit/4fc65fa935d47726295735e05ef8f8b65c12bdf2)an update to the getMessage() method in beta9. Maybe this is related to our issue?

**Comment by ManuelFernando** [comment] 2017-06-16 19:52
@averhaegen

**Comment by averhaegen** [comment] 2017-06-19 12:02
@ManuelFernando We tried the updated version but the issue is still present :( 
If we rollback to pubnub-angular2 1.0.0-beta.8 and pubnub 4.3.3, everything is working fine..

**Comment by ManuelFernando** [comment] 2017-06-19 19:26
@averhaegen we can’t roll back the version because after this there are a lot improvements and we can affect different stuffs  but if you can send a little demo where is the bug we can resolve, because this something very specific

**Comment by ManuelFernando** [comment] 2017-06-19 19:57
@averhaegen we could detect what is happening, we are going to introduce an extra method to release the channels used by getMessage. are you keeping your instance?

**Comment by jenscl** [comment] 2017-06-20 11:38
@ManuelFernando Yes, we use the default instance which is initialized in the root component of our application. Releasing the channels in our ngOnDestroy could indeed solve the problem.

**Comment by ManuelFernando** [comment] 2017-06-21 03:17
@jenscl @averhaegen please try with the new version, read the doc here in the repo the new method is called release is like clean but it’s going to resolve your stuffs

**Comment by jenscl** [comment] 2017-06-21 14:24
@ManuelFernando Thanks for implementing this new method, we already see improvements. However, there are still some things that do not work as expected:
- When releasing one channel (`this.pubnubService.release('device1');`) and subscribing again to it with getMessage (as in the code sample above), the history is loaded correctly. This is not the case when we try this with an array of channels (`this.pubnubService.release(['device1', 'device2']);`). The history does not show up when resubscribing to the channels.
- The history data is now loaded after resubscribing (one channel), but there's no new realtime data coming in afterwards.

Our ngOnDestroy now looks like this:
```
ngOnDestroy() {
    this.pubnubService.unsubscribe({ channels: ['device1'] });
    this.pubnubService.clean(['device1']);
    this.pubnubService.release('device1');
}
```

**Comment by ManuelFernando** [comment] 2017-06-21 15:10
@jenscl you have to release according to your subscribe this is equal to clean. For the example above if you are releasing you don’t need to clean, release will do both process. For example if you subscribe on getMessage ‘device1’ and [‘device1’, ‘device2’] although these subscription shared the channel: ‘device1’ are both different subscription and have to clean or release independently one to other.

**Comment by jenscl** [comment] 2017-06-21 16:05
@ManuelFernando Releasing them independently did solve our problems. We notice that the channels should be unsubscribed independently as well to make it work, even though we all subscribe to them at the same time (when passing array of channels, unsubscribeAll works too but we can't use it in our case).

Our ngOnDestroy code (for multiple channels) now looks like this:

```
ngOnDestroy() {
    for (let device of this.devices) {
        this.pubnubService.release(device);
        this.pubnubService.unsubscribe(device);
    }
}
```

Anyway thanks for your help, now everything works well.

**Closed** 2017-06-22 00:34 UTC
